-- Run this in Supabase SQL Editor before deploying the Vercel frontend.
-- The anon key is safe in the browser only because these policies are enabled.

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  alias text not null check (char_length(alias) between 1 and 80),
  display_name text not null default '',
  created_at timestamptz not null default now()
);

create table public.workouts (
  id bigint generated by default as identity primary key,
  external_id text unique,
  title text not null,
  kind text not null check (kind in ('Easy run', 'Intervals', 'Tempo', 'Long run', 'Recovery')),
  starts_at timestamptz not null,
  distance_km numeric not null check (distance_km > 0 and distance_km <= 500),
  duration_minutes integer not null check (duration_minutes > 0 and duration_minutes <= 10080),
  pace text not null,
  location text not null,
  notes text not null default '',
  translations jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.attendance (
  user_id uuid not null references auth.users(id) on delete cascade,
  workout_id bigint not null references public.workouts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, workout_id)
);

alter table public.profiles enable row level security;
alter table public.workouts enable row level security;
alter table public.attendance enable row level security;

create policy "Public can read workout schedule" on public.workouts for select using (true);
create policy "Members can read their profile" on public.profiles for select using (auth.uid() = id);
create policy "Members can create their profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Members can edit their profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "Members can read their own attendance" on public.attendance for select using (auth.uid() = user_id);
create policy "Members can join runs as themselves" on public.attendance for insert with check (auth.uid() = user_id);
create policy "Members can leave runs as themselves" on public.attendance for delete using (auth.uid() = user_id);

-- This view exposes only aggregate counts, never member IDs. Views run as the
-- owner by default, allowing public schedule visitors to see attendance totals
-- without granting them access to the attendance rows themselves.
create or replace view public.workout_attendee_counts as
  select workout_id, count(*)::integer as attendees
  from public.attendance
  group by workout_id;
grant select on public.workout_attendee_counts to anon, authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, alias, display_name)
  values (
    new.id,
    left(coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)), 80),
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
